default_context:
  project_name: 'nuskool'
  project_slug: 'nuskool'
  domain_main: 'nuskool.com'
  domain_staging: 'stag.nuskool.com'
  docker_swarm_stack_name_main: 'nuskool-com'
  docker_swarm_stack_name_staging: 'stag-nuskool-com'
  secret_key: 'beff552f35f916aaeda78a9be73431a82d22bd407f51fd2f230a7bf218b98385'
  first_superuser: 'admin@nuskool.com'
  first_superuser_password: 'qwQWasAS12!@'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.nuskool.com", "https://stag.nuskool.com", "https://nuskool.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: 'nuskool_smtp'
  smtp_password: 'qwQWasAS12!@'
  smtp_emails_from_email: 'info@nuskool.com'
  postgres_password: 'qwQWasAS12!@'
  pgadmin_default_user: 'admin@nuskool.com'
  pgadmin_default_user_password: 'qwQWasAS12!@'
  traefik_constraint_tag: 'nuskool.com'
  traefik_constraint_tag_staging: 'stag.nuskool.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:qwQWasAS12!@'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
